name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag raisen/bugzilla:$(date +%s)
    - name: Deploy to Docker Hub
      run: docker push raxon/bugzilla:$(date +%s)
