name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: raisen/bugzilla:latest
